import { launch, shot, BASE } from "./lib.mjs";
const FILE = process.env.APKG || "/mnt/user-data/uploads/All_decks-20261004095235.apkg";
const { browser, page, errors } = await launch();
const log = (...a) => console.log(...a);
await page.goto(BASE, { waitUntil: "networkidle" });
await page.click("text=Get started");
await page.click("text=Intermediate");
await page.click("text=Continue");
await page.click("text=Continue");
await page.click("text=Continue");
await page.click("text=Start learning");
await page.waitForSelector(".plan-hero");
await page.click("text=Import from Anki");
await page.waitForSelector("text=Select your .apkg file");
await shot(page, "30-import-pick");
const t0 = Date.now();
await page.setInputFiles('input[type="file"]', FILE);
await page.waitForSelector("text=/Found \\d+ decks?/", { timeout: 120000 });
log("parsed in ms:", Date.now() - t0);
await shot(page, "31-import-choose");
log((await page.innerText(".lesson-body")).slice(0, 900));
// say: first 315 RRTK known, 41 Kaishi known (stepper: click + until value)
const cards = page.locator(".lesson-body .card");
const n = await cards.count();
log("deck cards:", n);
await page.click("text=/Import \\d+ decks?/");
await page.waitForSelector("text=/Imported [\\d,]+ cards/", { timeout: 60000 });
await shot(page, "32-import-done");
await page.click("text=Start studying");
await page.waitForSelector(".flash", { timeout: 10000 });
await shot(page, "33-study-kanji");
log("errors:", errors);
await browser.close();
