import { launch, shot, BASE } from "./lib.mjs";
const { browser, page, errors } = await launch();
await page.goto(BASE, { waitUntil: "networkidle" });
await page.waitForSelector("text=Let's build your Japanese.", { timeout: 15000 });
await shot(page, "01-welcome");
await page.fill("#nm", "Mael");
await page.click("text=Get started");
await shot(page, "02-level");
await page.click("text=Intermediate");
await page.click("text=Continue");
await shot(page, "03-focus");
await page.click("text=Continue");
await shot(page, "04-time");
await page.click("text=Continue");
await shot(page, "05-known");
await page.click("text=Start learning");
await page.waitForSelector("text=Today's cards", { timeout: 10000 });
await shot(page, "06-home");
console.log("errors:", errors);
await browser.close();
