// Short original texts for the graded reader. Written for this app (not copied from anywhere).
// Each line is [Japanese with furigana markup, English]. Level 1 is the easiest.
// Difficulty is only a label: the reader measures how much of a text you already know.
const T = (id, level, jp, en, lines) => ({ id, level, jp, en, lines });

export const READER_LEVELS = { 1: "Starter", 2: "Easy", 3: "Medium", 4: "Stretch" };

export const PASSAGES = [
  // ---- level 1
  T("intro", 1, "自己紹介", "Introducing myself", [
    ["私[わたし]の名前[なまえ]はアンです。", "My name is Ann."],
    ["私[わたし]は学生[がくせい]です。", "I am a student."],
    ["日本語[にほんご]が好[す]きです。", "I like Japanese."],
    ["友達[ともだち]はスイスにいます。", "My friend is in Switzerland."],
    ["どうぞよろしくお願[ねが]いします。", "Nice to meet you."],
  ]),
  T("morning", 1, "私の朝", "My morning", [
    ["私[わたし]は毎朝[まいあさ]六時[ろくじ]に起[お]きます。", "I get up at six every morning."],
    ["朝[あさ]ご飯[はん]にパンと卵[たまご]を食[た]べます。", "For breakfast I eat bread and eggs."],
    ["それから、コーヒーを飲[の]みます。", "After that, I drink coffee."],
    ["七時[しちじ]半[はん]に家[いえ]を出[で]ます。", "I leave the house at half past seven."],
    ["学校[がっこう]まで電車[でんしゃ]で行[い]きます。", "I go to school by train."],
  ]),
  T("cafe", 1, "カフェで", "At the café", [
    ["今日[きょう]は友達[ともだち]とカフェに行[い]きました。", "Today I went to a café with a friend."],
    ["私[わたし]はコーヒーを飲[の]みました。", "I drank coffee."],
    ["友達[ともだち]は紅茶[こうちゃ]を飲[の]みました。", "My friend drank black tea."],
    ["ケーキも食[た]べました。", "We also ate cake."],
    ["ケーキはとてもおいしかったです。", "The cake was very delicious."],
  ]),
  T("family", 1, "私の家族", "My family", [
    ["私[わたし]は四人[よにん]家族[かぞく]です。", "My family has four people."],
    ["父[ちち]と母[はは]と弟[おとうと]がいます。", "There are my father, my mother and my younger brother."],
    ["父[ちち]は医者[いしゃ]です。", "My father is a doctor."],
    ["母[はは]は先生[せんせい]です。", "My mother is a teacher."],
    ["弟[おとうと]は十歳[じゅっさい]です。", "My younger brother is ten years old."],
  ]),
  T("weather", 1, "天気", "The weather", [
    ["今日[きょう]はいい天気[てんき]です。", "The weather is nice today."],
    ["空[そら]は青[あお]いです。", "The sky is blue."],
    ["でも、少[すこ]し寒[さむ]いです。", "But it is a little cold."],
    ["昨日[きのう]は雨[あめ]でした。", "Yesterday it was rainy."],
    ["明日[あした]は雪[ゆき]が降[ふ]ります。", "Tomorrow it will snow."],
  ]),
  T("room", 1, "私の部屋", "My room", [
    ["私[わたし]の部屋[へや]は小[ちい]さいです。", "My room is small."],
    ["部屋[へや]に机[つくえ]とベッドがあります。", "There is a desk and a bed in the room."],
    ["机[つくえ]の上[うえ]にパソコンがあります。", "There is a computer on the desk."],
    ["窓[まど]の近[ちか]くに本[ほん]がたくさんあります。", "There are many books near the window."],
    ["私[わたし]はこの部屋[へや]が好[す]きです。", "I like this room."],
  ]),
  // ---- level 2
  T("weekend", 2, "週末", "The weekend", [
    ["土曜日[どようび]に友達[ともだち]と映画[えいが]を見[み]ました。", "On Saturday I watched a movie with my friend."],
    ["映画[えいが]は面白[おもしろ]かったです。", "The movie was interesting."],
    ["その後[あと]で、レストランでご飯[はん]を食[た]べました。", "Afterwards we ate a meal at a restaurant."],
    ["日曜日[にちようび]は家[いえ]で勉強[べんきょう]しました。", "On Sunday I studied at home."],
    ["来週[らいしゅう]も友達[ともだち]に会[あ]いたいです。", "Next week I want to meet my friend again."],
  ]),
  T("shopping", 2, "買い物", "Shopping", [
    ["昨日[きのう]、駅[えき]の近[ちか]くの店[みせ]に行[い]きました。", "Yesterday I went to a shop near the station."],
    ["新[あたら]しいくつを買[か]いたかったです。", "I wanted to buy new shoes."],
    ["でも、とても高[たか]かったです。", "But they were very expensive."],
    ["だから、何[なに]も買[か]いませんでした。", "So I did not buy anything."],
    ["帰[かえ]りに、パンを買[か]いました。", "On the way home I bought bread."],
  ]),
  T("train", 2, "電車で", "On the train", [
    ["毎日[まいにち]、電車[でんしゃ]で学校[がっこう]に行[い]きます。", "I go to school by train every day."],
    ["電車[でんしゃ]の中[なか]で本[ほん]を読[よ]みます。", "I read a book on the train."],
    ["時々[ときどき]、音楽[おんがく]を聞[き]きます。", "Sometimes I listen to music."],
    ["今日[きょう]は人[ひと]がとても多[おお]かったです。", "Today there were very many people."],
    ["私[わたし]は立[た]っていました。", "I was standing."],
  ]),
  T("birthday", 2, "誕生日", "A birthday", [
    ["先週[せんしゅう]の金曜日[きんようび]は友達[ともだち]の誕生日[たんじょうび]でした。", "Last Friday was my friend's birthday."],
    ["私[わたし]はプレゼントに本[ほん]をあげました。", "I gave a book as a present."],
    ["友達[ともだち]は「ありがとう」と言[い]いました。", "My friend said \"thank you\"."],
    ["みんなでケーキを食[た]べて、歌[うた]を歌[うた]いました。", "Everyone ate cake and we sang a song."],
    ["楽[たの]しい一日[いちにち]でした。", "It was a fun day."],
  ]),
  T("school", 2, "学校で", "At school", [
    ["私[わたし]の学校[がっこう]は八時[はちじ]に始[はじ]まります。", "My school starts at eight."],
    ["午前[ごぜん]は数学[すうがく]と英語[えいご]を勉強[べんきょう]します。", "In the morning I study maths and English."],
    ["昼[ひる]ご飯[はん]は友達[ともだち]と食堂[しょくどう]で食[た]べます。", "I eat lunch with friends in the cafeteria."],
    ["午後[ごご]は体育[たいいく]があります。", "In the afternoon there is gym class."],
    ["体育[たいいく]の後[あと]は、いつもおなかがすきます。", "After gym class I am always hungry."],
  ]),
  // ---- level 3
  T("hobby", 3, "趣味", "A hobby", [
    ["私[わたし]の趣味[しゅみ]はボルダリングです。", "My hobby is bouldering."],
    ["週[しゅう]に二回[にかい]、ジムに行[い]きます。", "I go to the gym twice a week."],
    ["壁[かべ]を登[のぼ]るのは大変[たいへん]ですが、とても楽[たの]しいです。", "Climbing a wall is hard, but it is a lot of fun."],
    ["初[はじ]めは全然[ぜんぜん]できませんでした。", "At first I could not do it at all."],
    ["今[いま]は友達[ともだち]と一緒[いっしょ]に練習[れんしゅう]しています。", "Now I practice together with friends."],
  ]),
  T("sick", 3, "風邪", "A cold", [
    ["昨日[きのう]から風邪[かぜ]を引[ひ]いています。", "I have had a cold since yesterday."],
    ["頭[あたま]が痛[いた]いし、少[すこ]し熱[ねつ]もあります。", "My head hurts and I also have a bit of a fever."],
    ["だから、今日[きょう]は学校[がっこう]を休[やす]みました。", "So I stayed home from school today."],
    ["薬[くすり]を飲[の]んで、たくさん寝[ね]ました。", "I took medicine and slept a lot."],
    ["明日[あした]は元気[げんき]になるといいです。", "I hope I will be well tomorrow."],
  ]),
  T("cat", 3, "うちの猫", "Our cat", [
    ["私[わたし]の家[いえ]には猫[ねこ]がいます。", "There is a cat in my house."],
    ["名前[なまえ]はミケです。", "Her name is Mike."],
    ["ミケは毎朝[まいあさ]、私[わたし]が起[お]きる前[まえ]にベッドの上[うえ]に来[き]ます。", "Every morning, before I get up, Mike comes onto the bed."],
    ["ご飯[はん]がほしい時[とき]は、大[おお]きい声[こえ]で鳴[な]きます。", "When she wants food, she meows loudly."],
    ["かわいいので、私[わたし]は猫[ねこ]が大好[だいす]きです。", "She is so cute that I love cats."],
  ]),
  T("study", 3, "日本語の勉強", "Studying Japanese", [
    ["私[わたし]は一年[いちねん]前[まえ]から日本語[にほんご]を勉強[べんきょう]しています。", "I have been studying Japanese since a year ago."],
    ["毎日[まいにち]、三十分[さんじゅっぷん]ぐらい漢字[かんじ]を練習[れんしゅう]します。", "Every day I practice kanji for about thirty minutes."],
    ["漢字[かんじ]は難[むずか]しいですが、面白[おもしろ]いです。", "Kanji is difficult, but it is interesting."],
    ["日本[にほん]のアニメが好[す]きなので、もっと上手[じょうず]になりたいです。", "I like Japanese anime, so I want to get better."],
    ["日本語[にほんご]で友達[ともだち]と話[はな]せるようになりたいです。", "I want to become able to talk with friends in Japanese."],
  ]),
  T("kyoto", 3, "京都への旅行", "A trip to Kyoto", [
    ["夏休[なつやす]みに、家族[かぞく]と京都[きょうと]へ旅行[りょこう]しました。", "In the summer holidays I travelled to Kyoto with my family."],
    ["新幹線[しんかんせん]で行[い]ったので、とても速[はや]かったです。", "We went by Shinkansen, so it was very fast."],
    ["京都[きょうと]にはお寺[てら]がたくさんあります。", "There are many temples in Kyoto."],
    ["一番[いちばん]有名[ゆうめい]なお寺[てら]に行[い]って、写真[しゃしん]を撮[と]りました。", "We went to the most famous temple and took photos."],
    ["日本[にほん]の料理[りょうり]は本当[ほんとう]においしいと思[おも]いました。", "I thought Japanese food was truly delicious."],
    ["また行[い]きたいです。", "I want to go again."],
  ]),
  // ---- level 4
  T("lost", 4, "道に迷った", "Lost", [
    ["先週[せんしゅう]、知[し]らない町[まち]で道[みち]に迷[まよ]いました。", "Last week I got lost in a town I did not know."],
    ["地図[ちず]を見[み]ましたが、わかりませんでした。", "I looked at the map, but I did not understand it."],
    ["近[ちか]くにいた女[おんな]の人[ひと]に聞[き]いてみました。", "I tried asking a woman who was nearby."],
    ["その人[ひと]は親切[しんせつ]に駅[えき]まで案内[あんない]してくれました。", "She kindly guided me to the station."],
    ["おかげで、電車[でんしゃ]に間[ま]に合[あ]いました。", "Thanks to her, I made the train."],
  ]),
  T("dream", 4, "将来の夢", "A dream for the future", [
    ["私[わたし]の夢[ゆめ]は、ゲームを作[つく]る仕事[しごと]をすることです。", "My dream is to work making games."],
    ["そのために、毎日[まいにち]絵[え]を描[か]く練習[れんしゅう]をしています。", "For that, I practice drawing every day."],
    ["日本[にほん]のゲームが大好[だいす]きなので、いつか日本[にほん]で働[はたら]いてみたいです。", "I love Japanese games, so someday I would like to try working in Japan."],
    ["日本語[にほんご]が上手[じょうず]になったら、日本[にほん]の会社[かいしゃ]に手紙[てがみ]を書[か]くつもりです。", "When my Japanese gets good, I plan to write a letter to a Japanese company."],
    ["まだ先[さき]のことですが、頑張[がんば]ります。", "It is still a long way off, but I will do my best."],
  ]),
  T("festival", 4, "お祭り", "A festival", [
    ["夏[なつ]の夜[よる]、町[まち]でお祭[まつ]りがありました。", "On a summer night there was a festival in town."],
    ["浴衣[ゆかた]を着[き]ている人[ひと]がたくさんいました。", "There were many people wearing yukata."],
    ["友達[ともだち]と一緒[いっしょ]に屋台[やたい]で焼[や]きそばを買[か]って食[た]べました。", "With my friends I bought yakisoba at a stall and ate it."],
    ["最後[さいご]に、きれいな花火[はなび]を見[み]ました。", "At the end we watched beautiful fireworks."],
    ["来年[らいねん]もまた来[き]たいです。", "I want to come again next year too."],
  ]),
  T("letter", 4, "友達への手紙", "A letter to a friend", [
    ["元気[げんき]ですか。私[わたし]は元気[げんき]です。", "How are you? I am fine."],
    ["最近[さいきん]、日本語[にほんご]の勉強[べんきょう]が少[すこ]し楽[たの]しくなってきました。", "Recently studying Japanese has become a little more fun."],
    ["先週[せんしゅう]、初[はじ]めて日本語[にほんご]で手紙[てがみ]を書[か]きました。", "Last week I wrote a letter in Japanese for the first time."],
    ["間違[まちが]いがあったら、教[おし]えてください。", "If there are mistakes, please tell me."],
    ["また連絡[れんらく]します。", "I will be in touch again."],
  ]),
];

export const PASSAGE_BY_ID = Object.fromEntries(PASSAGES.map((p) => [p.id, p]));

/** Every word the texts use, so each one can be explained even if it is not in your decks. [word, reading, meaning] */
export const READER_WORDS = [
  ["名前", "なまえ", "name"], ["学生", "がくせい", "student"], ["日本語", "にほんご", "Japanese (language)"], ["好き", "すき", "fond of; to like"],
  ["友達", "ともだち", "friend"], ["スイス", "スイス", "Switzerland"], ["どうぞ", "どうぞ", "please; go ahead"], ["よろしく", "よろしく", "best regards"], ["お願い", "おねがい", "request; favor"],
  ["毎朝", "まいあさ", "every morning"], ["起きる", "おきる", "to get up; to wake up"], ["朝", "あさ", "morning"], ["ご飯", "ごはん", "rice; meal"], ["パン", "パン", "bread"],
  ["卵", "たまご", "egg"], ["食べる", "たべる", "to eat"], ["コーヒー", "コーヒー", "coffee"], ["飲む", "のむ", "to drink"], ["家", "いえ", "house; home"],
  ["出る", "でる", "to leave; to go out"], ["学校", "がっこう", "school"], ["電車", "でんしゃ", "train"], ["行く", "いく", "to go"],
  ["六時", "ろくじ", "six o'clock"], ["七時", "しちじ", "seven o'clock"], ["八時", "はちじ", "eight o'clock"], ["七時半", "しちじはん", "half past seven"],
  ["今日", "きょう", "today"], ["カフェ", "カフェ", "café"], ["紅茶", "こうちゃ", "black tea"], ["ケーキ", "ケーキ", "cake"], ["とても", "とても", "very"], ["おいしい", "おいしい", "delicious"],
  ["家族", "かぞく", "family"], ["四人", "よにん", "four people"], ["父", "ちち", "father (my)"], ["母", "はは", "mother (my)"], ["弟", "おとうと", "younger brother"],
  ["医者", "いしゃ", "doctor"], ["先生", "せんせい", "teacher"], ["十歳", "じゅっさい", "ten years old"],
  ["天気", "てんき", "weather"], ["いい", "いい", "good"], ["空", "そら", "sky"], ["青い", "あおい", "blue"], ["少し", "すこし", "a little"], ["寒い", "さむい", "cold"],
  ["でも", "でも", "but"], ["昨日", "きのう", "yesterday"], ["雨", "あめ", "rain"], ["明日", "あした", "tomorrow"], ["雪", "ゆき", "snow"], ["降る", "ふる", "to fall (rain, snow)"],
  ["部屋", "へや", "room"], ["小さい", "ちいさい", "small"], ["机", "つくえ", "desk"], ["ベッド", "ベッド", "bed"], ["上", "うえ", "top; above"], ["パソコン", "パソコン", "computer"],
  ["窓", "まど", "window"], ["近く", "ちかく", "nearby"], ["本", "ほん", "book"], ["たくさん", "たくさん", "many; a lot"],
  ["土曜日", "どようび", "Saturday"], ["映画", "えいが", "movie"], ["見る", "みる", "to see; to watch"], ["面白い", "おもしろい", "interesting; funny"], ["その後", "そのあと", "afterwards"],
  ["レストラン", "レストラン", "restaurant"], ["日曜日", "にちようび", "Sunday"], ["勉強", "べんきょう", "study"], ["来週", "らいしゅう", "next week"], ["会う", "あう", "to meet"],
  ["駅", "えき", "station"], ["店", "みせ", "shop"], ["新しい", "あたらしい", "new"], ["くつ", "くつ", "shoes"], ["買う", "かう", "to buy"], ["高い", "たかい", "expensive; tall"],
  ["だから", "だから", "so; therefore"], ["何", "なに", "what"], ["帰り", "かえり", "return; the way back"],
  ["毎日", "まいにち", "every day"], ["中", "なか", "inside"], ["読む", "よむ", "to read"], ["時々", "ときどき", "sometimes"], ["音楽", "おんがく", "music"], ["聞く", "きく", "to listen; to hear; to ask"],
  ["人", "ひと", "person"], ["多い", "おおい", "many"], ["立つ", "たつ", "to stand"],
  ["先週", "せんしゅう", "last week"], ["金曜日", "きんようび", "Friday"], ["誕生日", "たんじょうび", "birthday"], ["プレゼント", "プレゼント", "present"], ["あげる", "あげる", "to give"],
  ["言う", "いう", "to say"], ["みんな", "みんな", "everyone"], ["歌", "うた", "song"], ["歌う", "うたう", "to sing"], ["楽しい", "たのしい", "fun"], ["一日", "いちにち", "one day"],
  ["始まる", "はじまる", "to begin"], ["午前", "ごぜん", "morning (a.m.)"], ["数学", "すうがく", "mathematics"], ["英語", "えいご", "English (language)"], ["昼", "ひる", "noon; daytime"],
  ["食堂", "しょくどう", "cafeteria"], ["午後", "ごご", "afternoon"], ["体育", "たいいく", "physical education"], ["後", "あと", "after; later"], ["いつも", "いつも", "always"],
  ["おなか", "おなか", "stomach"], ["すく", "すく", "to become empty (hungry)"],
  ["趣味", "しゅみ", "hobby"], ["ボルダリング", "ボルダリング", "bouldering"], ["週", "しゅう", "week"], ["二回", "にかい", "twice"], ["ジム", "ジム", "gym"], ["壁", "かべ", "wall"],
  ["登る", "のぼる", "to climb"], ["大変", "たいへん", "tough; serious"], ["初め", "はじめ", "beginning; at first"], ["全然", "ぜんぜん", "not at all"], ["できる", "できる", "to be able to"],
  ["今", "いま", "now"], ["一緒", "いっしょ", "together"], ["練習", "れんしゅう", "practice"],
  ["風邪", "かぜ", "a cold"], ["引く", "ひく", "to pull; to catch (a cold)"], ["頭", "あたま", "head"], ["痛い", "いたい", "painful"], ["熱", "ねつ", "fever"], ["休む", "やすむ", "to rest; to be absent"],
  ["薬", "くすり", "medicine"], ["寝る", "ねる", "to sleep"], ["元気", "げんき", "well; healthy"], ["なる", "なる", "to become"],
  ["猫", "ねこ", "cat"], ["ミケ", "ミケ", "Mike (a cat's name)"], ["前", "まえ", "before; ago"], ["来る", "くる", "to come"], ["ほしい", "ほしい", "wanted; desirable"], ["時", "とき", "time; when"],
  ["大きい", "おおきい", "big"], ["声", "こえ", "voice"], ["鳴く", "なく", "to cry; to meow"], ["かわいい", "かわいい", "cute"], ["大好き", "だいすき", "to love; to like very much"],
  ["一年", "いちねん", "one year"], ["三十分", "さんじゅっぷん", "thirty minutes"], ["漢字", "かんじ", "kanji"], ["ぐらい", "ぐらい", "about"], ["難しい", "むずかしい", "difficult"],
  ["アニメ", "アニメ", "anime"], ["日本", "にほん", "Japan"], ["上手", "じょうず", "skilled; good at"], ["もっと", "もっと", "more"], ["話す", "はなす", "to speak"],
  ["夏休み", "なつやすみ", "summer vacation"], ["京都", "きょうと", "Kyoto"], ["旅行", "りょこう", "trip; to travel"], ["新幹線", "しんかんせん", "bullet train"], ["速い", "はやい", "fast"],
  ["お寺", "おてら", "temple"], ["一番", "いちばん", "most; number one"], ["有名", "ゆうめい", "famous"], ["写真", "しゃしん", "photo"], ["撮る", "とる", "to take (a photo)"],
  ["料理", "りょうり", "cooking; a dish"], ["本当", "ほんとう", "truth; really"], ["思う", "おもう", "to think"],
  ["知る", "しる", "to know"], ["町", "まち", "town"], ["道", "みち", "road; way"], ["迷う", "まよう", "to get lost"], ["地図", "ちず", "map"], ["わかる", "わかる", "to understand"],
  ["女", "おんな", "woman"], ["親切", "しんせつ", "kind"], ["案内", "あんない", "guidance; to guide"], ["くれる", "くれる", "to give (to me)"], ["おかげ", "おかげ", "thanks to"], ["間に合う", "まにあう", "to be in time"],
  ["夢", "ゆめ", "dream"], ["ゲーム", "ゲーム", "game"], ["作る", "つくる", "to make"], ["仕事", "しごと", "work; job"], ["ため", "ため", "purpose; sake"], ["絵", "え", "picture; drawing"],
  ["描く", "かく", "to draw"], ["いつか", "いつか", "someday"], ["働く", "はたらく", "to work"], ["会社", "かいしゃ", "company"], ["手紙", "てがみ", "letter"], ["書く", "かく", "to write"],
  ["つもり", "つもり", "intention"], ["まだ", "まだ", "still; yet"], ["先", "さき", "ahead; the future"], ["頑張る", "がんばる", "to do one's best"], ["こと", "こと", "thing; matter"],
  ["夏", "なつ", "summer"], ["夜", "よる", "night"], ["お祭り", "おまつり", "festival"], ["浴衣", "ゆかた", "summer kimono"], ["着る", "きる", "to wear"], ["屋台", "やたい", "food stall"],
  ["焼きそば", "やきそば", "fried noodles"], ["最後", "さいご", "the end; last"], ["きれい", "きれい", "pretty; clean"], ["花火", "はなび", "fireworks"], ["来年", "らいねん", "next year"], ["また", "また", "again"],
  ["最近", "さいきん", "recently"], ["初めて", "はじめて", "for the first time"], ["間違い", "まちがい", "mistake"], ["教える", "おしえる", "to teach; to tell"], ["連絡", "れんらく", "contact"],
].map(([f, r, m]) => ({ f, r, m }));
