// Generates src/springs.css: Material 3 Expressive spring tokens as CSS linear() easings.
// Step response of a damped spring (mass 1): stiffness k, damping ratio z.
import fs from "node:fs";
const TOKENS = {
  "fast-spatial": [1400, 0.6], spatial: [700, 0.8], "slow-spatial": [300, 0.8],
  "fast-effects": [3800, 1], effects: [1600, 1], "slow-effects": [800, 1],
};
const step = (k, z, t) => {
  const w = Math.sqrt(k);
  if (z >= 1) return 1 - Math.exp(-w * t) * (1 + w * t);
  const wd = w * Math.sqrt(1 - z * z);
  return 1 - Math.exp(-z * w * t) * (Math.cos(wd * t) + ((z * w) / wd) * Math.sin(wd * t));
};
let css = "/* generated by scripts/make-springs.mjs. Do not edit. */\n:root {\n";
for (const [name, [k, z]] of Object.entries(TOKENS)) {
  let T = 0.05;
  const ok = (t) => { for (let u = t; u < t + 2; u += 0.005) if (Math.abs(1 - step(k, z, u)) > 0.003) return false; return true; };
  while (!ok(T) && T < 3) T += 0.01;
  const n = Math.max(12, Math.min(40, Math.round(T * 60)));
  const pts = [];
  for (let i = 0; i <= n; i++) pts.push(+step(k, z, (T * i) / n).toFixed(4));
  pts[0] = 0; pts[n] = 1;
  css += `  --sp-${name}-d: ${Math.round(T * 1000)}ms;\n  --sp-${name}: linear(${pts.join(", ")});\n`;
  console.log(name, Math.round(T * 1000) + "ms", "peak", Math.max(...pts));
}
css += "}\n";
fs.writeFileSync("src/springs.css", css);
